import React from 'react';
import Header from "@/components/Header";
import Head from "next/head";
import Footer from "@/components/Footer";


// @ts-ignore
const Layout = ({children}) => {
    return (
        <div className="layout">
            <Head>
                <title>Lshop</title>
                 <meta name="description" content="Generated by create next app" /> 
                 <meta name="viewport" content="width=device-width, initial-scale=1" />
                 <link rel="icon" href="https://pngimg.com/d/letter_L_PNG103.png"/> 
            </Head>
            {/*<Header/>*/}
            <main>
                {children}
            </main>
            <Footer/>
        </div>
    );
};

export default Layout;